// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhlDEbM_70JrZflBE1HJyckg6XlWlDr5o',
    appId: '1:584344773990:web:107ffb5851f0b1419554a7',
    messagingSenderId: '584344773990',
    projectId: 'sehat-khidmat',
    authDomain: 'sehat-khidmat.firebaseapp.com',
    storageBucket: 'sehat-khidmat.firebasestorage.app',
    measurementId: 'G-3YBRPGJMRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnU6HUIXU4ojYusafKx29kPj-JInjFPFs',
    appId: '1:584344773990:android:e0f1bf7cd18c73449554a7',
    messagingSenderId: '584344773990',
    projectId: 'sehat-khidmat',
    storageBucket: 'sehat-khidmat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYNKx2ut5W6VEb9MtVYykZPGnpomMf4v8',
    appId: '1:584344773990:ios:84fb43095583e5169554a7',
    messagingSenderId: '584344773990',
    projectId: 'sehat-khidmat',
    storageBucket: 'sehat-khidmat.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYNKx2ut5W6VEb9MtVYykZPGnpomMf4v8',
    appId: '1:584344773990:ios:84fb43095583e5169554a7',
    messagingSenderId: '584344773990',
    projectId: 'sehat-khidmat',
    storageBucket: 'sehat-khidmat.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhlDEbM_70JrZflBE1HJyckg6XlWlDr5o',
    appId: '1:584344773990:web:524b76d202408b059554a7',
    messagingSenderId: '584344773990',
    projectId: 'sehat-khidmat',
    authDomain: 'sehat-khidmat.firebaseapp.com',
    storageBucket: 'sehat-khidmat.firebasestorage.app',
    measurementId: 'G-DHEX5TJCCH',
  );
}
